FROM node:24-slim

WORKDIR /app

COPY package*.json .

RUN npm install

COPY . .

ENV VITE_API_BASE_URL=""
ENV VITE_CLOUDINARY_CLOUD_NAME="dgfntqxtc"
ENV VITE_MAP_KEY="AIzaSyAzRV7WS3pwwLHm5tJr6T7rGpP4BAIUu-0"

EXPOSE 3000

CMD [ "npm","run","dev" ]