FROM node:24-slim AS builder

WORKDIR /build

COPY package*.json .

RUN npm ci

COPY . .

ENV VITE_API_BASE_URL=""
ENV VITE_CLOUDINARY_CLOUD_NAME='dgfntqxtc'
ENV VITE_MAP_KEY="AIzaSyAzRV7WS3pwwLHm5tJr6T7rGpP4BAIUu-0"

RUN npm run build




FROM nginx:1.29.3 AS runner

RUN rm -rf /usr/nginx/share/html/*

COPY --from=builder /build/dist/ /usr/nginx/share/html/

EXPOSE 80

CMD [ "nginx","-g","daemon off;" ]