services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    image: cotraveller_server:dev
    container_name: cotraveller_dev_server
    expose:
      - 8080
    volumes:
      - ./server:/app
      - /app/node_modules/
    networks:
      - cotraveller_dev_net
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    image: cotraveller_client:dev
    container_name: cotraveller_dev_client
    expose:
      - 3000
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - cotraveller_dev_net
    restart: unless-stopped
    depends_on:
      - server

  nginx:
    image: nginx:1.29.3
    container_name: cotraveller_dev_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - cotraveller_dev_net
    restart: unless-stopped
    depends_on:
      - client
      - server

networks:
  cotraveller_dev_net:
