services:
  server:
    image: ghcr.io/prathamguptacode/cotraveller-server:latestHashedTag
    expose:
      - "8080"
    container_name: cotraveller_server
    networks:
      - cotraveller_net
    restart: unless-stopped

  client:
    image: ghcr.io/prathamguptacode/cotraveller-client:latestHashedTag
    expose:
      - "80"
    container_name: cotraveller_client
    networks:
      - cotraveller_net
    restart: unless-stopped
    env_file:
      - ./server/.env.production
    volumes:
      - ./nginx/client.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - server

  nginx:
    image: nginx:1.29.3
    ports:
      - "80:80"
      - "443:443"
    container_name: cotraveller_nginx
    networks:
      - cotraveller_net
    restart: unless-stopped
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - certbot_certificates:/etc/letsencrypt
    depends_on:
      - client

volumes:
  certbot_certificates:

networks:
  cotraveller_net: