FROM node:24-slim AS builder

WORKDIR /build

COPY package*.json .

RUN npm ci

COPY . .

RUN npm run build



FROM node:24-slim AS runner

WORKDIR /app

COPY package*.json .

RUN npm ci --omit=dev

COPY --from=builder /build/dist/ /app/dist/

EXPOSE 8080

CMD [ "npm","start"]
